version: '3.7'

services:
  php:
    image: anatolygladkikh/php7.4.3:prod
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - main
  web:
    image: nginx:alpine
    volumes:
      - ./public:/app/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - main
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    working_dir: /data/postgresql
    networks:
      - main
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - main

networks:
  main:

volumes:
  pgdata:
